#!/usr/bin/env python
#-*-coding:utf-8-*-
name_dict = {
	u"高佳琦" :'gjq',
	"gaojiaqi" : 'gjq',
	"gjq" : 'gjq',
	u"厉丹阳" : 'ldy',
	"lidaoyang" : 'ldy',
	"ldy" : 'ldy',
	u"韩纪飞" : 'hjf',
	"hanjifei" : 'hjf',
	"hjf" : 'hjf',
	"韩纪飞-信息所":'hjf',
	u"郭东旭" : 'gdx',
	"guodongxu" : 'gdx',
	"gdx" : 'gdx',
	u"韩晓霏" : 'hxf',
	"hanxiaofei" : 'hxf',
	"hxf" : 'hxf',
	"韩晓霏-控理所":'hxf',
	u"张若冰" : 'zrb',
	"zhangruobing" : 'zrb',
	"zrb" : 'zrb',
	"张若冰-系统所": 'zrb',
	u"徐凯源" : 'xky',
	"xukaiyuan" : 'xky',
	"xky" : 'xky',
	u"刘洋"   : 'ly',
	"liuyang" : 'ly',
	"ly" : 'ly',
	u"王佳林" : 'wjl',
	"wangjialin" : 'wjl',
	"wjl" : 'wjl',
	u"林声远" : 'lsy',
	"linshengyuan" : 'lsy',
	"yyj" : 'lsy',
	"yyg" : 'lsy',
	"lsy" : 'lsy',
	u"于超"   : 'yc',
	"yuchao" : 'yc',
	"ryanyu" : 'yc',
	"ry" : 'yc',
	"yc" : 'yc',
	u"宋绍铭" : 'ssm',
	"ssm" : 'ssm',
	"songshaoming" : 'ssm',
	"宋绍铭-信息所":'ssm',
	u"韦洁"   : 'wj',
	"weijie" : 'wj',
	"wj" : 'wj',
	u"陈佳宁" : 'cjn',
	u"陳佳寧" : 'cjn',
	"chenjianing" : 'cjn',
	"cjn" : 'cjn',
	u"机器人" : 'test',
}

name_abbr = {
	'xky',
	'ssm',
	'ly',
	'hjf',
	'gjq',
	'gdx',
	'zrb',
	'hxf',
	'yc',
	'lsy',
	'test',
	'ldy',
	'wjl',
	'wj',
	'cjn',
}